spring.application.name=mascotas-alertas
server.port=8080


spring.data.mongodb.uri=${MONGODB_URI:mongodb+srv://arturoosoriom_db_user:Proyecto123@dsosorio.qgwu3gu.mongodb.net/mascotasalertas?retryWrites=true&w=majority&appName=DSOsorio}


app.alert.default-radius-km=1.0
app.alert.target-latency-ms=5000
